services:
  app-prod:
    image: bloglist-frontend-prod
    build: 
      context: ./bloglist-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    container_name: bloglist-frontend-prod

  bloglist-backend-prod:
    image: bloglist-backend-prod
    build: 
      context: ./bloglist-backend/
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-backend/:/usr/src/app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_URL=${DATABASE_URL}
    container_name: bloglist-backend-prod
    ports:
      - 3003:3003

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy-prod
    depends_on:
      - app-prod # wait for the frontend container to be started

  postgres:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: postgres
