services:
  app-dev:
    image: bloglist-frontend-dev
    build: 
      context: ./bloglist-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    container_name: bloglist-frontend-dev
  # debug-helper:
  #   image: busybox

  bloglist-backend-dev:
    image: bloglist-backend-dev
    build: 
      context: ./bloglist-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-backend/:/usr/src/app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_URL=postgres://postgres:salasana@postgres:5432/postgres
      - TEST_MONGODB_URI=${TEST_MONGODB_URI}
    container_name: bloglist-backend-dev
    ports:
      - 3000:3000

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy-dev
    depends_on:
      - app-dev # wait for the frontend container to be started

  postgres:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: postgres
